Home Work Done
pureplatform-bootcamp/playground pull request #11
Opened 2022-11-03 05:14 UTC by mamer12

2022-11-03 14:57 UTC, ssharba requested changes

2022-11-03 14:57 UTC, ssharba commented on app/controllers/addresses_controller.rb
> +      address.update(
can we user address_params here just like create?

2022-11-03 22:08 UTC, mamer12 commented on app/controllers/addresses_controller.rb
> +      address.update(
Yes, but I'm updating the address based on the address id so it will be more accurate

2022-11-04 01:15 UTC, ssharba commented on app/controllers/addresses_controller.rb
> +      address.update(
try this 
address.update(address_params), I wan't talking about id. just replace line 16

2022-11-04 19:20 UTC, ssharba approved these changes

2022-11-04 19:22 UTC, merged